name       : libgnome-games-support
version    : 1.6.0.1
release    : 5
source     :
    - https://download.gnome.org/sources/libgnome-games-support/1.6/libgnome-games-support-1.6.0.1.tar.xz : a82536edc22c0d1c4fa4247ae2dfed5d6bdf63f0df9c088167c392d78a9c2e76
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : library intended for use by GNOME Games
description: |
    libgnome-games-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
