name       : libgnome-games-support
version    : 1.8.1
release    : 7
source     :
    - https://download.gnome.org/sources/libgnome-games-support/1.8/libgnome-games-support-1.8.1.tar.xz : c37b7acd3ba7eb12207f5d7bb020535fa5783b0bd897e51b2bd629ce119a413f
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : library intended for use by GNOME Games
description: |
    libgnome-games-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
