name       : libgnome-games-support
version    : 1.4.3
release    : 3
source     :
    - https://download.gnome.org/sources/libgnome-games-support/1.4/libgnome-games-support-1.4.3.tar.xz : 704a7a93aa5066f84738b60d696cf393dfbbf1a3e339f9adbb40af0cf70eca3c
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : library intended for use by GNOME Games
description: |
    libgnome-games-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
