name       : libgnome-games-support
version    : 1.2.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgnome-games-support/1.2/libgnome-games-support-1.2.1.tar.xz : a626396c72603add6bae1ab0b5bee1d58657cc7e232b1fe6fda746b960715ee7
license    :
    - GPL-3.0
    - LGPL-3.0
component  : desktop.library
summary    : library intended for use by GNOME Games
description: |
    libgnome-games-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
