name       : libgnome-games-support
version    : 1.8.0
release    : 6
source     :
    - https://download.gnome.org/sources/libgnome-games-support/1.8/libgnome-games-support-1.8.0.tar.xz : abdde538a14fd6078fe6b7e6e93f38a33491d9bec711a116d8b47530184cb3dd
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : library intended for use by GNOME Games
description: |
    libgnome-games-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
