name       : libgnome-games-support
version    : 1.4.1
release    : 2
source     :
    - https://download.gnome.org/sources/libgnome-games-support/1.4/libgnome-games-support-1.4.1.tar.xz : 61430205046e0df843bafca9ab341d3678c1939d7c047b2fb28f26c12c73f4c8
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : library intended for use by GNOME Games
description: |
    libgnome-games-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
