name       : libgnome-games-support
version    : 1.4.4
release    : 4
source     :
    - https://download.gnome.org/sources/libgnome-games-support/1.4/libgnome-games-support-1.4.4.tar.xz : f8a6ae569868abb4e90cf48e505dff527a635cb21a4af33039379860b3ad6bfe
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : library intended for use by GNOME Games
description: |
    libgnome-games-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
